### ISSUE TITLE
Error On Deployment

### ISSUE THREAD

**Issue by LockChainCEO** [OffchainLabs/orbit-setup-script#14]
Hello
I am on step 6 https://orbit.arbitrum.io/deployment?step=6

I have deployed on VPS with 

PRIVATE_KEY="0xmykey" L2_RPC_URL="https://goerli-rollup.arbitrum.io/rpc" L3_RPC_URL="http://91.191.214.70:8449" yarn run setup

Error occurred: Error: could not detect network (event="noNetwork", code=NETWORK_ERROR, version=providers/5.7.2)
    at Logger.makeError (/root/orbit-setup-script/node_modules/@ethersproject/logger/src.ts/index.ts:269:28)
    at Logger.throwError (/root/orbit-setup-script/node_modules/@ethersproject/logger/src.ts/index.ts:281:20)
    at JsonRpcProvider.<anonymous> (/root/orbit-setup-script/node_modules/@ethersproject/providers/src.ts/json-rpc-provider.ts:483:23)
    at step (/root/orbit-setup-script/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:48:23)
    at Object.throw (/root/orbit-setup-script/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:29:53)
    at rejected (/root/orbit-setup-script/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:21:65)
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  reason: 'could not detect network',
  code: 'NETWORK_ERROR',
  event: 'noNetwork'
}

Could you tell me how to fix this error?

Thank you

**Comment by AtharvDesignString** [comment]
Yes I am also facing the similar issue

**Comment by AtharvDesignString** [comment]
I changed L3_PRC_URL to http://127.0.0.1:8449
now its working

**Comment by rassbuilldr** [comment]
> I changed L3_PRC_URL to http://127.0.0.1:8449 now its working

I will try. Do you mind sharing your VPS RPC?

**Comment by AtharvDesignString** [comment]
I created on local server

**Comment by AtharvDesignString** [comment]
Hey @rassbuilldr I set up new chain on VPS and I figured out what was the issue with me I guess you also facing the similar one. Can you tell me after running the docker which containers are running?

**Comment by LockChainCEO** [comment]
> Hey @rassbuilldr I set up new chain on VPS and I figured out what was the issue with me I guess you also facing the similar one. Can you tell me after running the docker which containers are running?

I torn down that server Im going to try to use mainnet. If youd like to collab shoot me a msg on TG https://t.me/blockchainreg

**Comment by kamalbuilds** [comment]
hi @AtharvDesignString @LockChainCEO were you guys able to find a solution to this problem ?

I am facing the same , tried a bunch of things but they didnt work !

**Comment by kamalbuilds** [comment]
hi @AtharvDesignString @LockChainCEO were you guys able to find a solution to this problem ?

I am facing the same , tried a bunch of things but they didnt work !

**Comment by AtharvDesignString** [comment]
Yes @kamalbuilds , Can you tell me which are all the containers are running?

**Comment by LockChainCEO** [comment]
> 

Yes I got support on discord. Send me a Msg on tg https://t.me/blockchainreg

**Comment by y0unghe** [comment]
I am trying on my local mac, facing the same error.

**Comment by TucksonDev** [comment]
Hey all, there are multiple reasons that might cause a "could not detect network" error. To name a few: port not accessible in the RPC server (if different from local), the nitro docker container not running, other networking issues, ...
As the original issue was resolved, I'm going to close this ticket. @y0unghe , I suggest you reach out to us on [Discord](https://discord.gg/arbitrum), where we have a specific channel to help out with orbit related issues (orbit-support).
Thanks!

**Comment by umershaikh123** [comment]
Getting the same error for holesky chain , the l3 rpc url solution did not work

**Comment by Randomacy** [comment]
> I changed L3_PRC_URL to http://127.0.0.1:8449 now its working

Doesn't work for me, still have the same error
