### ISSUE TITLE
docker compose up failed, services with 'depends_on' cannot be extended

### ISSUE THREAD

**Issue by wojijiwo** [OffchainLabs/orbit-setup-script#55]
also with error, services with 'depends_on' cannot be extended

env:
Ubuntu 22.04.3 LTS (GNU/Linux 5.15.0-83-generic x86_64)
node: v20.11.0
npm: 10.2.4
docker-compose version 1.29.2, build unknown

**Comment by boldkoala4615** [comment]
Make sure to install docker compose > v2 and use `docker compose up -d` (instead of `docker-compose`)
